<a href="https://colab.research.google.com/github/dibyanshu999/Python-libraries/blob/main/numpy_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy


In [ ]:
#hi world

In [ ]:
print("hi")

hi


In [ ]:
#numpy turtorial

numerical python

In [ ]:
import numpy as np

In [ ]:
from time import process_time

In [ ]:
python_list = [i for i in range(10000)]
start_time= process_time()
python_list=[i+5 for i in python_list]
end_time= process_time()
print(end_time-start_time)

0.0011189830000000178


In [ ]:
np_array = np.array([i for i in range (10000)])
start_time= process_time()

np_array+=5
end_time= process_time()
print(end_time-start_time)

0.00020151199999984826


numpy arrays

In [ ]:
lst1=[1,2,3,4,5]
print(lst1)
type(lst1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)
#np arrays are similar to  matrices

[1 2 3 4 5]


numpy.ndarray

creating 1d array

In [ ]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
#2d array
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
c= np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial placeholders in numpy arrays

In [ ]:
#create a numpy array of zeroes
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array of 1s
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#array of a particular value
p=np.full((5,5),5)
print(p)


[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
#create an identity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a numpy array of random values btw 0 and 1
b=np.random.random((3,4))
print(b)

[[0.59622983 0.92275586 0.03912063 0.18457752]
 [0.26547618 0.09177816 0.96952048 0.09147754]
 [0.7878904  0.41638896 0.63970673 0.93665513]]


In [ ]:
#random integer value of the array within a specific range
c= np.random.randint(10,100,(3,5))   # range=(10,100), dimension =3,5
print(c)

[[64 46 63 30 14]
 [12 31 69 79 68]
 [73 56 23 35 43]]


In [ ]:
#array of evenly spaced values , specifying the no of values
d= np.linspace(10,30,5) # no of values=5
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
 #array of evenly spaced values , mentioning the step size
 e= np.arange(10,30,5)   #step size =5
 print(e)

[10 15 20 25]


In [ ]:
#convert a list to an array
lst2= [1,2,3,4,5]

np_array=np.asarray(lst2)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Analysing a numpy array

In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)

[[66 75 42 41 12]
 [73 10 49 26 68]
 [35 89 82 30 22]
 [74 45 32 54 14]
 [72 16 88 77 75]]


In [ ]:
#array dimension
print(c.shape)

(5, 5)


In [ ]:
# no of dimensions
print(c.ndim)

2


In [ ]:
#no of values in an array
print(c.size)

25


In [ ]:
#checking the data type of values in the array
print(c.dtype)

int64


mathematical operation on np array


In [ ]:
lst1=[1,2,3,4,5]
lst2=[5,6,7,8,9]
print(lst1+lst2)
#concatenation on adding

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[8 2 7]
 [6 9 4]
 [1 8 8]]
[[16 11 18]
 [17 16 18]
 [17 12 18]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[24 13 25]
 [23 25 22]
 [18 20 26]]
[[ -8  -9 -11]
 [-11  -7 -14]
 [-16  -4 -10]]
[[128  22 126]
 [102 144  72]
 [ 17  96 144]]
[[0.5        0.18181818 0.38888889]
 [0.35294118 0.5625     0.22222222]
 [0.05882353 0.66666667 0.44444444]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))

[[24 13 25]
 [23 25 22]
 [18 20 26]]
[[ -8  -9 -11]
 [-11  -7 -14]
 [-16  -4 -10]]


array manipulation

In [ ]:
#transpose
trans=np.transpose(a)
print(trans)
print(a.shape)

[[8 6 1]
 [2 9 8]
 [7 4 8]]
(3, 3)


In [ ]:
b=np.random.randint(10,20,(3,2))
print(b)
trans=np.transpose(b)
print(trans)
print(b.shape)
print(trans.shape)


[[12 14]
 [17 11]
 [18 12]]
[[12 17 18]
 [14 11 12]]
(3, 2)
(2, 3)


In [ ]:
#reshaping an array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 9 2]
 [1 3 8]]
(2, 3)


In [ ]:
b=a.reshape(3,2)
print(b)

[[7 9]
 [2 1]
 [3 8]]
